check exit status

diff --git a/.github/workflows/prerelease.yml b/.github/workflows/prerelease.yml
--- a/.github/workflows/prerelease.yml
+++ b/.github/workflows/prerelease.yml
@@ -29,4 +29,8 @@ jobs:
           git pull 
           pnpm install 
           pnpm run build
+          if [ $? -ne 0 ]; then
+            echo "pnpm build failed"
+            exit 1
+          fi
         ENDSSH
